#pragma once
#include "GameObject.h"

#define MARIO_WALKING_SPEED		0.01f 
//0.1f
#define MARIO_JUMP_SPEED_Y		0.05f
#define MARIO_JUMP_DEFLECT_SPEED 0.2f
#define MARIO_GRAVITY			0.001f
#define MARIO_DIE_DEFLECT_SPEED	 0.5f

#define MARIO_STATE_IDLE			0
#define MARIO_STATE_WALKING_RIGHT	100
#define MARIO_STATE_WALKING_LEFT	200
#define MARIO_STATE_JUMP			300
#define MARIO_STATE_DIE				400

#define MARIO_STATE_IDLE_LEFT		1
#define MARIO_STATE_IDLE_RIGHT		2
#define MARIO_STATE_WALKING_LEFT		3
#define MARIO_STATE_WALKING_RIGHT		4
#define MARIO_STATE_SLIDE_LEFT		5
#define MARIO_STATE_SLIDE_RIGHT		6
#define MARIO_STATE_JUMP_LEFT		7
#define MARIO_STATE_JUMP_RIGHT		8
#define MARIO_STATE_SKID_LEFT		9
#define MARIO_STATE_SKID_RIGHT		10
#define MARIO_STATE_RUN_LEFT		11
#define MARIO_STATE_RUN_RIGHT		12
#define MARIO_STATE_RUNJUMP_LEFT		13
#define MARIO_STATE_RUNJUMP_RIGHT		14
#define MARIO_STATE_HOLD_LEFT		15
#define MARIO_STATE_HOLD_RIGHT		16
#define MARIO_STATE_KICK_LEFT		17
#define MARIO_STATE_KICK_RIGHT		18
#define MARIO_STATE_SWIMIDLE_LEFT		19
#define MARIO_STATE_SWIMIDLE_RIGHT		20
#define MARIO_STATE_SWIMINPUT_LEFT		21
#define MARIO_STATE_SWIMINPUT_RIGHT		22
#define MARIO_STATE_CLIMB_LEFT		23
#define MARIO_STATE_CLIMB_RIGHT		24
#define MARIO_STATE_PIPE		25
#define MARIO_STATE_DIE		26


//ANIMATION SMALL MARIO

#define MARIO_ANIMATION_SMALL_IDLE_LEFT		0
#define MARIO_ANIMATION_SMALL_IDLE_RIGHT		1
#define MARIO_ANIMATION_SMALL_WALKING_LEFT		2
#define MARIO_ANIMATION_SMALL_WALKING_RIGHT		3
#define MARIO_ANIMATION_SMALL_SLIDE_LEFT		4
#define MARIO_ANIMATION_SMALL_SLIDE_RIGHT		5
#define MARIO_ANIMATION_SMALL_JUMP_LEFT		6
#define MARIO_ANIMATION_SMALL_JUMP_RIGHT		7
#define MARIO_ANIMATION_SMALL_SKID_LEFT		8
#define MARIO_ANIMATION_SMALL_SKID_RIGHT		9
#define MARIO_ANIMATION_SMALL_RUN_LEFT		10
#define MARIO_ANIMATION_SMALL_RUN_RIGHT		11
#define MARIO_ANIMATION_SMALL_RUNJUMP_LEFT		12
#define MARIO_ANIMATION_SMALL_RUNJUMP_RIGHT		13
#define MARIO_ANIMATION_SMALL_HOLD_LEFT		14
#define MARIO_ANIMATION_SMALL_HOLD_RIGHT		15
#define MARIO_ANIMATION_SMALL_KICK_LEFT		16
#define MARIO_ANIMATION_SMALL_KICK_RIGHT		17
#define MARIO_ANIMATION_SMALL_SWIMIDLE_LEFT		18
#define MARIO_ANIMATION_SMALL_SWIMIDLE_RIGHT		19
#define MARIO_ANIMATION_SMALL_SWIMINPUT_LEFT		20
#define MARIO_ANIMATION_SMALL_SWIMINPUT_RIGHT		21
#define MARIO_ANIMATION_SMALL_CLIMB_LEFT		22
#define MARIO_ANIMATION_SMALL_CLIMB_RIGHT		23
#define MARIO_ANIMATION_SMALL_PIPE		24
#define MARIO_ANIMATION_SMALL_DIE		25

//ANIMATION SUPER MARIO

#define MARIO_ANIMATION_SUPER_IDLE_LEFT		26
#define MARIO_ANIMATION_SUPER_IDLE_RIGHT		27
#define MARIO_ANIMATION_SUPER_WALKING_LEFT		28
#define MARIO_ANIMATION_SUPER_WALKING_RIGHT		29
#define MARIO_ANIMATION_SUPER_DUCK_LEFT		30
#define MARIO_ANIMATION_SUPER_DUCK_RIGHT		31
#define MARIO_ANIMATION_SUPER_SLIDE_LEFT		32
#define MARIO_ANIMATION_SUPER_SLIDE_RIGHT		33
#define MARIO_ANIMATION_SUPER_JUMP_LEFT		34
#define MARIO_ANIMATION_SUPER_JUMP_RIGHT		35
#define MARIO_ANIMATION_SUPER_SKID_LEFT		36
#define MARIO_ANIMATION_SUPER_SKID_RIGHT		37
#define MARIO_ANIMATION_SUPER_THROW_LEFT		38
#define MARIO_ANIMATION_SUPER_THROW_RIGHT		39
#define MARIO_ANIMATION_SUPER_RUN_LEFT		40
#define MARIO_ANIMATION_SUPER_RUN_RIGHT		41
#define MARIO_ANIMATION_SUPER_RUNJUMP_LEFT		42
#define MARIO_ANIMATION_SUPER_RUNJUMP_RIGHT		43
#define MARIO_ANIMATION_SUPER_HOLD_LEFT		44
#define MARIO_ANIMATION_SUPER_HOLD_RIGHT		45
#define MARIO_ANIMATION_SUPER_KICK_LEFT		46
#define MARIO_ANIMATION_SUPER_KICK_RIGHT		47
#define MARIO_ANIMATION_SUPER_SWIMIDLE_LEFT		48
#define MARIO_ANIMATION_SUPER_SWIMIDLE_RIGHT		49
#define MARIO_ANIMATION_SUPER_SWIMINPUT_LEFT		50
#define MARIO_ANIMATION_SUPER_SWIMINPUT_RIGHT		51
#define MARIO_ANIMATION_SUPER_CLIMB_LEFT		52
#define MARIO_ANIMATION_SUPER_CLIMB_RIGHT		53
#define MARIO_ANIMATION_SUPER_PIPE		54
#define MARIO_ANIMATION_SUPER_DOOR		55
#define MARIO_ANIMATION_SUPER_SPIN_LEFT		56
#define MARIO_ANIMATION_SUPER_SPIN_RIGHT		57
#define MARIO_ANIMATION_SUPER_BONK_LEFT		58
#define MARIO_ANIMATION_SUPER_BONK_RIGHT		59
#define MARIO_ANIMATION_SUPER_LOOKUP_LEFT		60
#define MARIO_ANIMATION_SUPER_LOOKUP_RIGHT		61
#define MARIO_ANIMATION_SUPER_GROW_LEFT		62
#define MARIO_ANIMATION_SUPER_GROW_RIGHT		63
#define MARIO_ANIMATION_SUPER_SHRINK_LEFT		64
#define MARIO_ANIMATION_SUPER_SHRINK_RIGHT		65

//ANIMATION FIRE MARIO

#define MARIO_ANIMATION_FIRE_IDLE_LEFT		66
#define MARIO_ANIMATION_FIRE_IDLE_RIGHT		67
#define MARIO_ANIMATION_FIRE_WALKING_LEFT		68
#define MARIO_ANIMATION_FIRE_WALKING_RIGHT		69
#define MARIO_ANIMATION_FIRE_DUCK_LEFT		70
#define MARIO_ANIMATION_FIRE_DUCK_RIGHT		71
#define MARIO_ANIMATION_FIRE_SLIDE_LEFT		72
#define MARIO_ANIMATION_FIRE_SLIDE_RIGHT		73
#define MARIO_ANIMATION_FIRE_JUMP_LEFT		74
#define MARIO_ANIMATION_FIRE_JUMP_RIGHT		75
#define MARIO_ANIMATION_FIRE_SKID_LEFT		76
#define MARIO_ANIMATION_FIRE_SKID_RIGHT		77
#define MARIO_ANIMATION_FIRE_THROW_LEFT		78
#define MARIO_ANIMATION_FIRE_THROW_RIGHT		79
#define MARIO_ANIMATION_FIRE_RUN_LEFT		80
#define MARIO_ANIMATION_FIRE_RUN_RIGHT		81
#define MARIO_ANIMATION_FIRE_RUNJUMP_LEFT		82
#define MARIO_ANIMATION_FIRE_RUNJUMP_RIGHT		83
#define MARIO_ANIMATION_FIRE_HOLD_LEFT		84
#define MARIO_ANIMATION_FIRE_HOLD_RIGHT		85
#define MARIO_ANIMATION_FIRE_KICK_LEFT		86
#define MARIO_ANIMATION_FIRE_KICK_RIGHT		87
#define MARIO_ANIMATION_FIRE_SWIMIDLE_LEFT		88
#define MARIO_ANIMATION_FIRE_SWIMIDLE_RIGHT		89
#define MARIO_ANIMATION_FIRE_SWIMINPUT_LEFT		90
#define MARIO_ANIMATION_FIRE_SWIMINPUT_RIGHT		91
#define MARIO_ANIMATION_FIRE_CLIMB_LEFT		92
#define MARIO_ANIMATION_FIRE_CLIMB_RIGHT		93
#define MARIO_ANIMATION_FIRE_PIPE		94
#define MARIO_ANIMATION_FIRE_DOOR		95
#define MARIO_ANIMATION_FIRE_SPIN_LEFT		96
#define MARIO_ANIMATION_FIRE_SPIN_RIGHT		97

//ANIMATION RACCOON MARIO

#define MARIO_ANIMATION_REACCOON_IDLE_LEFT		98
#define MARIO_ANIMATION_REACCOON_IDLE_RIGHT		99
#define MARIO_ANIMATION_REACCOON_WAG_LEFT		102
#define MARIO_ANIMATION_REACCOON_WAG_RIGHT		103
#define MARIO_ANIMATION_REACCOON_WALKING_LEFT		100
#define MARIO_ANIMATION_REACCOON_WALKING_RIGHT		101
#define MARIO_ANIMATION_REACCOON_DUCK_LEFT		104
#define MARIO_ANIMATION_REACCOON_DUCK_RIGHT		105
#define MARIO_ANIMATION_REACCOON_SLIDE_LEFT		106
#define MARIO_ANIMATION_REACCOON_SLIDE_RIGHT		107
#define MARIO_ANIMATION_REACCOON_JUMP_LEFT		108
#define MARIO_ANIMATION_REACCOON_JUMP_RIGHT		109
#define MARIO_ANIMATION_REACCOON_SKID_LEFT		110
#define MARIO_ANIMATION_REACCOON_SKID_RIGHT		111
#define MARIO_ANIMATION_REACCOON_THROW_LEFT		112
#define MARIO_ANIMATION_REACCOON_THROW_RIGHT		113
#define MARIO_ANIMATION_REACCOON_RUN_LEFT		114
#define MARIO_ANIMATION_REACCOON_RUN_RIGHT		115
#define MARIO_ANIMATION_REACCOON_RUNJUMP_LEFT		116
#define MARIO_ANIMATION_REACCOON_RUNJUMP_RIGHT		117
#define MARIO_ANIMATION_REACCOON_FLY_LEFT		118
#define MARIO_ANIMATION_REACCOON_FLY_RIGHT		119
#define MARIO_ANIMATION_REACCOON_HOLD_LEFT		120
#define MARIO_ANIMATION_REACCOON_HOLD_RIGHT		121
#define MARIO_ANIMATION_REACCOON_KICK_LEFT		122
#define MARIO_ANIMATION_REACCOON_KICK_RIGHT		123
#define MARIO_ANIMATION_REACCOON_SWIMIDLE_LEFT		124
#define MARIO_ANIMATION_REACCOON_SWIMIDLE_RIGHT		125
#define MARIO_ANIMATION_REACCOON_SWIMINPUT_LEFT		126
#define MARIO_ANIMATION_REACCOON_SWIMINPUT_RIGHT		127
#define MARIO_ANIMATION_REACCOON_CLIMB_LEFT		128
#define MARIO_ANIMATION_REACCOON_CLIMB_RIGHT		129
#define MARIO_ANIMATION_REACCOON_PIPE		130
#define MARIO_ANIMATION_REACCOON_DOOR		131
#define MARIO_ANIMATION_REACCOON_SPIN_LEFT		132
#define MARIO_ANIMATION_REACCOON_SPIN_RIGHT		133


#define MARIO_ANI_BIG_IDLE_RIGHT		0
#define MARIO_ANI_BIG_IDLE_LEFT			1
#define MARIO_ANI_SMALL_IDLE_RIGHT		2
#define MARIO_ANI_SMALL_IDLE_LEFT			3

#define MARIO_ANI_BIG_WALKING_RIGHT			4
#define MARIO_ANI_BIG_WALKING_LEFT			5
#define MARIO_ANI_SMALL_WALKING_RIGHT		6
#define MARIO_ANI_SMALL_WALKING_LEFT		7

#define MARIO_ANI_DIE				8

#define	MARIO_LEVEL_SMALL	1
#define	MARIO_LEVEL_BIG		2
#define	MARIO_LEVEL_BIG		2
#define	MARIO_LEVEL_FIRE	3
#define	MARIO_LEVEL_RACCOON	4

#define MARIO_BIG_BBOX_WIDTH  16
#define MARIO_BIG_BBOX_HEIGHT 32

#define MARIO_SMALL_BBOX_WIDTH  16
#define MARIO_SMALL_BBOX_HEIGHT 16

#define MARIO_UNTOUCHABLE_TIME 5000
#define MARIO_SKID_TIME 200


class CMario : public CGameObject
{
	int level;
	int untouchable;
	int money = 0;
	DWORD untouchable_start;

	float start_x;			// initial position of Mario at scene
	float start_y; 
public: 
	DWORD skid_start;


	bool isJump = false;
	bool iswalking = false;
	bool isBonusvy = true;
	bool ispressX = false;
	bool isjumpX = false;
	bool iscanjumpS = false;
	bool isUpS = true;
	float power = 0.0f;
	bool isRun = false;
	bool isSkid = false;

	CMario(float x = 0.0f, float y = 0.0f);
	virtual void Update(DWORD dt, vector<LPGAMEOBJECT> *colliable_objects = NULL);
	virtual void Render();

	void SetState(int state);
	void SetLevel(int l) { level = l; }
	void StartUntouchable() { untouchable = 1; untouchable_start = GetTickCount64(); }

	void Reset();

	virtual void GetBoundingBox(float &left, float &top, float &right, float &bottom);
	void DecreasePower();
	void IncreasePower();
	bool ColitionWithObjectStatic(vector<LPGAMEOBJECT>* listObject = NULL);

};